--- 
translations: 
  :logout: Вийти
  :signup: Зареєструватись
  :login: Залогуватись
  :search: Пошук
  :users: Користувачі
  :new_posts: Нові записи
  :tags: Теги
  :monitoring: Під наглядом
  :blocked_users: Блокування користувачів
  :black_list: Чорний список
  :favorites: Улюблені
  :admin_tasks: Адміністрування
  :powered_by: Двігло